### ISSUE TITLE
RepairEncoding, Test-BrokenEncoding, and Multiple Encodings 

### ISSUE THREAD

**Issue by Tharkis** [brianary/Detextive#1]
I was playing around with Detextive in hopes that it would help fix an issue where my data is undergoing encodings from UTF-8 to Windows-1252 multiple times. 

It didn't seem to fix that issue directly, but it did revert the first level of encoding. So, I thought I could run it in a loop with a check using Test-BrokenEncoding to see if the encoding was still bad. Unfortunately, this didn't work either as Test-BrokenEncoding returns "false". 

Is this expected behavior and if so, do you have any suggestions on how I might be able to solve my issue? 

Here's the logic I am using:
```
[string]$UnicodeString = 'Multiplication Sign: Ãƒâ€” (2 Encodings)'
#[string]$UnicodeString = 'Multiplication Sign: Ã— (Single Encoded)'
[bool]$EncodingBad = [System.Convert]::ToBoolean(($UnicodeString1 | Test-BrokenEncoding))
[int]$LoopCount = 0

While ($EncodingBad -eq $true -and $LoopCount -le 5 ) {
    write-host "String Before Repair: "$UnicodeString
    write-host "Encoding Bad: "$EncodingBad
    $UnicodeString = $UnicodeString | Repair-Encoding
    $EncodingBad = [System.Convert]::ToBoolean(($UnicodeString | Test-BrokenEncoding))
    write-host "String After Repair: "$UnicodeString
    write-host "Encoding Bad: "$EncodingBad
    $LoopCount++
}
return $UnicodeString
```

This is the output:
```
String Before Repair:  Multiplication Sign: Ãƒâ€” (2 Encodings)
Encoding Bad:  True
String After Repair:  Multiplication Sign: Ã— (2 Encodings)
Encoding Bad:  False
Multiplication Sign: Ã— (2 Encodings)
```

Thanks in advance!

**Comment by brianary** [comment]
I'll have to run some testing, but this does seem like a reasonable use case. It may even be possible to detect the double-encoding itself, though the repair may be a bit more involved. This could take a few days to pin down.

Thanks for reporting this!

**Comment by brianary** [comment]
It looks like the [decomposition normalization step](https://github.com/brianary/Detextive/blob/1a98e297fc9143713172139dcd883eb9789e8f32/src/Detextive/RepairEncodingCommand.fs#L47 "(fun s -> s.Normalize(NormalizationForm.FormKD))") ([`FormKD`](https://docs.microsoft.com/dotnet/api/system.text.normalizationform "Indicates that a Unicode string is normalized using full compatibility decomposition.")) is getting in the way of iterative repair. I need to check some of the tests to see if removing it will cause other issues.

**Comment by Tharkis** [comment]
Thanks for looking into this so quickly.

**Comment by brianary** [comment]
Version 1.1.4 should address this now. I've broken the normalization out to a separate cmdlet.

**Comment by Tharkis** [comment]
I just finished testing the new cmdlet and it appears to address my use case. 

Thank you so much for the quick turnaround, this will help me quite a bit!
